name: cibuilder runner dind
description: run cibuilder in a cibuilder net and docker-in-docker service

inputs:
  run_cmd:
    description: cibuilder command (check|build|test|deploy|all)
    required: true
  bin_ref:
    description: cibuilder bin ref (branch, tag)
    required: false
    default: ""
  image:
    description: cibuilder image
    required: false
    default: docker.io/stack4ops/cibuilder:rootless

runs:
  using: composite
  steps:
    - name: Run cibuilder
      shell: bash
      run: |
        "${{ github.action_path }}/run.sh" \
          "${{ inputs.run_cmd }}" \
          "${{ inputs.bin_ref }}" \
          "${{ inputs.image }}"
